### ISSUE TITLE
Check Game Message packets subtypes 0x00 and 0x08

### ISSUE THREAD

**Issue by IvanSanchez** [rjwut/ArtClientLib#33]
With Glitter, I'm seeing out-of-the-ordinary behaviour with the game messages (type 0xf754c8fe). I no longer receive GameStart (subtype 0x00) packets, but I do receive a subtype 0x08 at game start instead.

On a related note, I seem to no longer receive the subtype 0x04 when the server pauses/unpauses.

I suggest we investigate this a bit further.

**Comment by rjwut** [comment]
Have you observed anything new with this issue with version 2.1.5?

**Comment by IvanSanchez** [comment]
I haven't tried this with 2.1.5 (life is busy for me, too ;-) )

**Comment by rjwut** [comment]
So I've been digging into this a bit now (not on 2.1.5 yet). I'm connecting as a science console, and I am seeing the same phenomenon as you: the packet currently denoted as GameStartPacket doesn't seem to ever get sent, but the mysterious subtype `0x08` one does, its payload consisting of what appears to be a single int (0). This might vary from console to console, so I'm going to play around with this some more and see what I can learn.

I think I'm going to start a page on the wiki where we document the specific sets of packets that occur with particular game events (on connect when game is not running, on simulation start, on connect when game is in progress, etc.).

**Comment by rjwut** [comment]
Okay, so this is strange. I noticed that when the game starts, the `0x08` sends `00 00 00 00` in its payload, but when I fire a torpedo, it sends `00 00 c8 42`, which corresponds to the float value 100.0. I have no idea what it means, but I have to agree that this packet probably does not indicate that the game has started. I haven't yet noticed it being emitted for any other events.

As for the apparent disappearance of the `GameStartPacket`, the only conclusion I can reach is that it was deemed unnecessary. It was a good way to tell whether the simulation started before or after the client clicked "Ready," but the `PausePacket` kind of already does that. In any case, I don't know that most clients would even care about that: in either case; they just want to know when to start rendering, getting`SkyboxPacket` or `DifficultyPacket` does that.

**Comment by rjwut** [comment]
At this point, I think the best thing to do is officially remove `GameStartPacket`. The `0x08` one I think remains unknown for now; we just don't know enough about it to say anything definitive.
