### ISSUE TITLE
please publish this library to a maven repository

### ISSUE THREAD

**Issue by amir-arad** [rjwut/ArtClientLib#46]
Hi

I want to use this library as a dependency for an integration server. is it possible to publish this project to some public maven repository upon successfull builds / releases?

**Comment by rjwut** [comment]
Life has been pretty busy, so I haven't had a whole lot of time to work on this again until recently. I've set up my local workspace to build the pom.xml file. For the moment, I haven't bothered to try to reorganize the project to conform to the typical Maven directory structure. I'll need to do some tests and I would like to get some other bugs done at the same time, but hopefully I'll put this out before too much longer. I've never pushed anything to Maven Central before, so this will be a learning experience.

**Comment by rjwut** [comment]
Because of the potential messiness of doing this, especially since I'd like to reorganize the project structure to conform to Maven's conventions, I've decided to do this in a separate release.

**Comment by amir-arad** [comment]
solved in IAN
