### ISSUE TITLE
Two issues with GameMasterMessagePacket.java

### ISSUE THREAD

**Issue by briandurney** [rjwut/ArtClientLib#47]
I found two issues with GameMasterMessagePacket: src/net/dhleong/acl/protocol/core/GameMasterMessagePacket.java

First issue:
When I sent a GameMasterMessagePacket to a program using the ArtClientLib I got a packet parsing exception.  I'm pretty sure that's caused by line 42 in GameMasterMessagePacket.java, where it tries to read an int for the console number instead of reading a byte.
Line 42 is currently:
        int console = reader.readInt();
and should be:
        int console = reader.readByte();

https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol:-GameMasterMessagePacket says that the Console field is a byte.

I can post a stack trace for this if that would be helpful.

Second Issue:
In the GameMasterMessagePacket(String sender, String message, Console console) constructor, which starts on line 76, the check for a valid console number should only be done if the console parameter is not null.  Passing in a null Console parameter means the message should go to the COMM station as a normal COMM message, but the console number check will crash on a NullPointerException if null is passed in.

Thanks for looking at these issues.
--Brian Durney

**Comment by rjwut** [comment]
Sorry for taking so long to respond to this; life has been pretty busy for me lately. Thanks for this report. I'll have a look.

**Comment by rjwut** [comment]
I've fixed this issue and will push it to the repo as soon as Comcast decides to send someone out to fix my Internet service. ;P

**Comment by briandurney** [comment]
Thanks for fixing that.
Brian Durney

On Apr 15, 2015, at 4:42 PM, Robert J. Walker <notifications@github.com<mailto:notifications@github.com>> wrote:


I've fixed this issue and will push it to the repo as soon as Comcast decides to send someone out to fix my Internet service. ;P
