### ISSUE TITLE
Apply pull request #45 to 2.5.0 branch

### ISSUE THREAD

**Issue by rjwut** [rjwut/ArtClientLib#53]
@karafelix has provided pull request #45. Unfortunately, I hadn't created the 2.5.0 branch at that time, so the request is pointed at master. I want these changes to be part of the 2.5.0 release, so I need to apply them there.

**Comment by IvanSanchez** [comment]
You can actually do a manual merge - define a git remote for @karafelix's repo with `git remote add`, and then `git checkout master; git merge karafelix/master`.
