### ISSUE TITLE
NpcUpdatePacket unknowns

### ISSUE THREAD

**Issue by mrfishie** [rjwut/ArtClientLib#54]
**I'm no longer updating this list here. Please see [the issue on the node-artemis repo](https://github.com/mrfishie/node-artemis/issues/12).**

The [NpcUpdatePacket](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket) still has many unknown bits.

I've done some experimenting to figure out what some of them mean, and I thought it might be useful to dump some info here... (note that all of these values were found in scripted games, so things might differ for other types)

In order of how probable these descriptions are...

**[Bit 1.2](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-12-float) (float)** (unknown1 in glitter) appears to be the impulse/throttle amount for the ship. I guess this is so the client can display the streams behind the engines, and simulate the movement of the ship smoothly.

**[Bit 3.6](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-36-byte) (byte)** (unknown6 in glitter) looks like it is the fleet number (the one set in a mission file). Found by changing the fleet number in the mission editor. This is a bit puzzling since we already have side number ([bit 4.2](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#side-bit-42-int)), although looking in the mission editor there is a property for all entities called sideValue and then one for enemies and NPCs called fleet number.

**[Bit 4.4](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-44-byte) (byte)** (unknown8 in glitter) might be the side of the ship (again, the one set in a mission file). Also found by changing the side in the mission editor. It looks like 1 is enemy and 2 is player (the same values used in a mission file). Might be more useful than the friend/enemy flag in PvP/scripted games?

**[Bit 4.3](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-43-int) (int)** (unknown7 in glitter), **[bit 4.5](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-45-byte) (byte)** (unknown9 in glitter) and **[bit 4.6](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-46-byte) (byte)** (unknown10 in glitter) all seem to be related to the ship type (i.e neutral or enemy in the mission editor). For enemy NPCs, bit 4.3 is almost always -1, but sometimes 0. For neutrals, unknown 7 is either not present 0, and occasionally -1 (but normally the -1 is set after a few ticks). Could be something to do with dive/rise, but using an int for that seems a bit weird. Bits 4.5 and 4.6 both appear to give values of -1 for neutrals, and other values including -1 for enemies. I think that they might have something to do with AI.

**[Bit 2.8](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-28-short) (short)** (unknown4 in glitter) doesn't seem to normally be sent with the initial 'creation' packet. Through a bit of testing with the mission editor, I think it might be whether the shields are on (i.e shields are on by default, and setting this to 0 turns them off?). I haven't done enough testing to confirm this though.

**[Bit 4.7](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-47-byte) (byte)** (unknown11 in glitter) always seems to be 1 from my testing. Maybe this could have something to do with dive/rise? (although I think [bit 4.3](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-43-int) is more likely to be that)

**[Bit 5.1](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-51-int) (int)** (unknown13 in glitter) and **[bit 5.2](https://github.com/rjwut/ArtClientLib/wiki/Artemis-Packet-Protocol%3A-NpcUpdatePacket#unknown-bit-52-int) (int)** (unknown14 in glitter) always seem to either be omitted or 0.

**Things that are missing:** mission files allow a ship exit point to be configured, however this doesn't _seem_ to have any effect on the packet. Additinally, changing the surrender chance doesn't seem to change anything. Race and hull keys appear to be missing from the currently documented packet, although the client might not need them. They would have to be a pair of values (one for race keys and one for hull keys), so could be bits 4.5 and 4.6 or 5.1 and 5.2?

The mission editor has a property to determine if a ship triggers mines, which doesn't appear to affect any values in the packet.

Some other testing and feedback would be gladly appreciated!

**Comment by mrfishie** [comment]
Through some experimenting, it appears as though bit 1.2 does control the simulated movement of the ship, but doesn't control the graphical streams behind the ship, meaning you end up with something like this when the ship isn't moving:
![streams](http://i.imgur.com/IrjUsxp.jpg)

**Comment by rjwut** [comment]
Thanks for the info. I'm adding the first two items to ArtClientLib, since they seem to be sufficiently understood. (I think the distinction between side and fleet is that you can have multiple fleets on the same side, but I'm not sure about this.) Once those changes are released, I intend to close this issue; feel free to open another one if you discover the purpose for any of the other fields.
