### ISSUE TITLE
WeapPlayerUpdatePacket and EngPlayerUpdatePacket missing

### ISSUE THREAD

**Issue by Hackmancoltaire** [rjwut/ArtClientLib#56]
Initially I was trying to use the SystemManager to determine the torpedo status of the main player ship. The torpedo count always came back as "-1" and so this lead me to try to listen for WeapPlayerUpdatePacket packets. But no matter what activity happens between the server and client I don't seem to have any of those packets coming across.

I've tried listening for those packets specifically and also tried listening for all packets and then manually parsing the output.

Using latest 2.5.0 branch against Artemis 2.1.1.

**Comment by Hackmancoltaire** [comment]
Ok. Running as a client the SystemMgr doesn't give me any information about the torpedo status. Likely because these packets aren't recognized. BUT, when running as a proxy I do get that information. Any idea why?

**Comment by rjwut** [comment]
Are you selecting any consoles with one or more `SetConsolePacket`s? If so, which ones? `WeapPlayerUpdatePacket`s and `EngPlayerUpdatePacket`s don't get sent to every console.

**Comment by Hackmancoltaire** [comment]
When in client mode I tried with several consoles, including weapons.

**Comment by rjwut** [comment]
The [v2.5.0 release](https://github.com/rjwut/ArtClientLib/tree/v2.5.0) includes a number of bug fixes. I'll give it a try with that release in the next few days, but if you get time before I have a chance to test it, try dropping in the new JAR and see if it makes any difference.

**Comment by rjwut** [comment]
Whoops, I gave the wrong URL for the link in the previous comment; I've updated it to the correct one.
