### ISSUE TITLE
Determine why build 63 failed

### ISSUE THREAD

**Issue by rjwut** [rjwut/ArtClientLib#58]
TravisCI is complaining that [VesselDataTest is failing](https://travis-ci.org/rjwut/ArtClientLib/jobs/69515144). The weird thing is, all tests pass just fine on my box. This might have to do with how resources are packaged during the build.

**Comment by Hackmancoltaire** [comment]
I develop on a Mac, so I don't have Artemis installed at all. So I had to include the VesselData.xml manually in the compiled JAR, and then used:
VesselData.load(new File("."));

**Comment by rjwut** [comment]
The default vesselData.xml file is supposed to be packaged in the JAR. If you don't use VesselData.load(File), it's supposed to load that one automatically. I recently added .snt parsing and bundled the default .snt files in the JAR as well, so there might be something going on there.

**Comment by rjwut** [comment]
The latest released JAR does have the vesselData.xml packaged in it and it works fine for me, as did the builds. It's when I added the new code that also parses .snt files (and which obliged me to refactor how file loading works) that I ran into problems with the build, even though it still works on my box. Separator character issue, perhaps?

**Comment by rjwut** [comment]
Resources weren't getting copied in the build script.
