### ISSUE TITLE
Artemis 2.3.0 released

### ISSUE THREAD

**Issue by JordanLongstaff** [rjwut/ArtClientLib#61]
I'm sure you're already working on this, but Artemis 2.3.0 was released yesterday and the current version of ArtClientLib is not compatible. Please update to support the new version.

**Comment by JordanLongstaff** [comment]
Specifically, what seems to be happening now is every time a connection made, it's immediately lost. It looks to me like what was supposed to happen was ArtClientLib is supposed to disconnect from any previous server before connecting to another server, but this seems to be happening in reverse order.

**Comment by JordanLongstaff** [comment]
OK, no, I see the problem now. The receiver thread catches an IllegalArgumentException with the message "No ObjectType with this ID: 68". It may be because of what's been added to Artemis 2.3.0 (including player-controlled fighters).

**Comment by Hackmancoltaire** [comment]
Any update on this?

**Comment by rjwut** [comment]
Work has been done on it. It's still in process as I'm attempting to track down some info on some of the new packets.

**Comment by Hackmancoltaire** [comment]
I'm planning on needing this near the end of the month (27-30). If there's anything I can do to help I'd be happy to. You should post your current progress and I can help diagnose the new packets.

**Comment by rjwut** [comment]
I'm been writing about my progress in the Artemis forums: http://artemis.forumchitchat.com/post/artclientlib-will-become-ian-for-artemis-2-3-dev-blog-thread-7934973?&trail=15

It should be noted that I'm making some major changes with this upcoming release, including renaming the project to better reflect its evolution. It will now be called IAN (Interface for Artemis Networking). See the thread for more details.

**Comment by Hackmancoltaire** [comment]
Heya. You'd indicated in the forum that you were in the testing phase, any chance you can commit stuff so others can test too? I have a con that I'll need the framework for starting Friday, and I have LOTS of time to test and help make improvements.

**Comment by rjwut** [comment]
I've released the source for the latest version of the library (https://github.com/rjwut/ian) and will make a binary release soon.
